name: sofia
description: "Un nuevo proyecto Flutter."
# La siguiente línea evita que el paquete se publique accidentalmente en
# pub.dev usando `flutter pub publish`. Esto es preferible para paquetes privados.
publish_to: 'none' # Elimina esta línea si deseas publicar en pub.dev

# Las siguientes líneas definen la versión y número de compilación de tu aplicación.
# Un número de versión consta de tres números separados por puntos, como 1.2.43
# seguido de un número de compilación opcional separado por +.
# Tanto la versión como el número de compilación pueden anularse en flutter
# build especificando --build-name y --build-number, respectivamente.
# En Android, build-name se usa como versionName mientras que build-number se usa como versionCode.
# Lee más sobre versionado en Android en https://developer.android.com/studio/publish/versioning
# En iOS, build-name se usa como CFBundleShortVersionString mientras que build-number se usa como CFBundleVersion.
# Lee más sobre versionado en iOS en
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# En Windows, build-name se usa para las partes mayor, menor y de parche
# de las versiones de archivo de producto mientras que build-number se usa como sufijo de compilación.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Las dependencias especifican otros paquetes que tu paquete necesita para funcionar.
# Para actualizar automáticamente las dependencias de tu paquete a las versiones más recientes
# considera ejecutar `flutter pub upgrade --major-versions`. Alternativamente,
# las dependencias se pueden actualizar manualmente cambiando los números de versión a continuación
# a la versión más reciente disponible en pub.dev. Para ver qué dependencias tienen versiones más recientes
# disponibles, ejecuta `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Las siguientes líneas agregan la fuente Cupertino Icons a tu aplicación.
  # Úsalo con la clase CupertinoIcons para iconos de estilo iOS.
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  http: ^1.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.6
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.2
  flutter_contacts: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

  # El paquete "flutter_lints" a continuación contiene un conjunto de lints recomendados para
  # fomentar buenas prácticas de codificación. El conjunto de lints proporcionado por el paquete está
  # activado en el archivo `analysis_options.yaml` ubicado en la raíz de tu
  # paquete. Consulta ese archivo para obtener información sobre cómo desactivar lints específicos
  # y activar otros.
  flutter_lints: ^6.0.0

# Para obtener información sobre la parte genérica de Dart en este archivo, consulta
# la siguiente página: https://dart.dev/tools/pub/pubspec

# La siguiente sección es específica de los paquetes de Flutter.
flutter:

  # La siguiente línea asegura que la fuente Material Icons esté
  # incluida en tu aplicación, para que puedas usar los iconos en
  # la clase Icons de material.
  uses-material-design: true

  # Para agregar recursos a tu aplicación, agrega una sección de recursos, así:
  assets:
    - assets/logo.png

  # Un recurso de imagen puede referirse a uno o más "variantes" específicas de resolución, consulta
  # https://flutter.dev/to/resolution-aware-images

  # Para obtener más detalles sobre cómo agregar recursos de dependencias de paquetes, consulta
  # https://flutter.dev/to/asset-from-package

  # Para agregar fuentes personalizadas a tu aplicación, agrega una sección de fuentes aquí,
  # en esta sección "flutter". Cada entrada en esta lista debe tener una
  # clave "family" con el nombre de la familia de fuentes, y una clave "fonts" con una
  # lista que proporciona el recurso y otros descriptores para la fuente. Por
  # ejemplo:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Para obtener más detalles sobre fuentes de dependencias de paquetes,
  # consulta https://flutter.dev/to/font-from-package

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-MediumItalic.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
